#!/bin/bash
store() {
    file=$1
    pid=$2
    format=$3
    OBJDIR='.dip/objects'
    sha=$(shasum -a 256 ${file} | awk '{print $1}')
    d1=${sha:0:2}
    d2=${sha:2:2}
    fn=${sha:4}
    mkdir -p ${OBJDIR}/${d1}/${d2} 
    cp ${file} ${OBJDIR}/${d1}/${d2}/${fn}
    tag ${sha} ${pid}
    sysmeta ${file} ${pid} ${format}
    echo ${sha}
}

tag() {
    cid=$1
    value=$2
    taghash=$(echo -n ${value} |shasum -a 256 |awk '{print $1}')
    tagfile=".dip/refs/tags/${taghash}"
    echo -n ${cid} > ${tagfile}
    echo " ${value}" >> ${tagfile}
    cat ${tagfile}
}

sysmeta() {
    file=${1}
    pid=$2
    format=$3
    template='../sysmeta-template'
    cid=$(shasum -a 256 ${file} | awk '{print $1}')
    pidhash=$(echo -n ${pid} |shasum -a 256 |awk '{print $1}')
    pidfile=".dip/sysmeta/${pidhash}"
    isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
    size=$(stat -f "%z" ${file})
    cat ${template} | PID=${pid} \
        SHA256=${cid} \
        ISODATE=${isodate} \
        SIZE=${size} \
        FILENAME=$(basename ${file}) \
        FORMAT_ID=${format} \
        envsubst > ${pidfile}
}
