#!/bin/bash
store() {
    file=$1
    pid=$2
    format=$3
    sha=$(shasum -a 256 ${file} | awk '{print $1}')
    OBJDIR=".dip/objects/${sha:0:2}/${sha:2:2}"
    mkdir -p ${OBJDIR}
    cp ${file} ${OBJDIR}/${sha:4}
    tag ${sha} ${pid}
    sysmeta ${file} ${pid} ${format}
    echo ${sha}
}

tag() {
    cid=$1
    value=$2
    taghash=$(echo -n ${value} |shasum -a 256 |awk '{print $1}')
    tagdir=".dip/refs/tags/${taghash:0:2}/${taghash:2:2}"
    mkdir -p ${tagdir}
    tagfile="${tagdir}/${taghash:4}"
    echo -n ${cid} > ${tagfile}
    echo " ${value}" >> ${tagfile}
    cat ${tagfile}
}

sysmeta() {
    file=${1}
    pid=$2
    format=$3
    template='../sysmeta-template'
    cid=$(shasum -a 256 ${file} | awk '{print $1}')
    pidhash=$(echo -n ${pid} |shasum -a 256 |awk '{print $1}')
    piddir=".dip/sysmeta/${pidhash:0:2}/${pidhash:2:2}"
    mkdir -p ${piddir}
    pidfile="${piddir}/${pidhash:4}"
    isodate=$(date +"%Y-%m-%dT%H:%M:%S%z")
    size=$(stat -f "%z" ${file})
    cat ${template} | PID=${pid} \
        SHA256=${cid} \
        ISODATE=${isodate} \
        SIZE=${size} \
        FILENAME=$(basename ${file}) \
        FORMAT_ID=${format} \
        envsubst > ${pidfile}
}
